name: screenshot_callback_fix
description: Flutter plugin that allows you to detect mobile screenshot and execute callback functions on iOS and Android.
version: 0.0.4
homepage: https://github.com/LiuDongCai/flutter_screenshot_callback

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  plugin:
    platforms:
      android:
        package: com.flutter.moum.screenshot_callback
        pluginClass: ScreenshotCallbackPlugin
      ios:
        pluginClass: ScreenshotCallbackPlugin
